apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    user: admin
    password: password
    url: http://influxdb:8086
    basicAuth: true
    jsonData:
      dbName: influx
    secureJsonData:
      username: admin
      password: admin